fullnameOverride: profile

service:
  type: ClusterIP
  port: 80

k8sProbes:
  enable: true
  livenessProbe:
    path: actuator/health
    port: http
    initialDelaySeconds: 290
    periodSeconds: 15
    timeoutSeconds: 3
    failureThreshold: 3
  readinessProbe:
    path: actuator/health
    port: http
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 20
    failureThreshold: 3
    successThreshold: 3
  startupProbe:
    path: actuator/health
    port: http   
